# run with `uv run python -m dev.gen_tables`
"""Regenerate ``fairfetched/get/_chembl_tables.py`` from the latest ChEMBL schema.

The generated ``ChemblTables`` mix-in lists one ``table(name)`` descriptor per
table in the latest published ``schema_documentation.txt``, so a language server
and ``dir()`` expose the full table set. Older releases that lack (or predate) a
listed table raise ``AttributeError`` only on access.
"""

from pathlib import Path

from fairfetched.get import chembl
from dev.check_missing_tables import extract_tables, fetch_schema_doc

OUT = Path(__file__).parents[1] / "fairfetched" / "get" / "_chembl_tables.py"

# names owned by _Base / Chembl; a table of the same name stays at lfs["<name>"].
RESERVED = {
    "version",
    "raw_paths",
    "parquet_paths",
    "dir",
    "module",
    "name",
    "sources",
    "lfs",
    "view",
    "raw_sql_db_path",
}

HEADER = '''\
# generated by `uv run python -m dev.gen_tables` from the ChEMBL {version} schema.
# do not edit by hand.
"""Raw ChEMBL source tables as attributes on :class:`fairfetched.get.Chembl`."""

from polars import LazyFrame

from fairfetched.get._tables import table


class ChemblTables:
'''


def main() -> None:
    version = chembl.latest()
    doc = fetch_schema_doc(version)
    if not doc:
        raise SystemExit(f"could not fetch schema documentation for chembl {version}")
    tables = sorted(t.lower() for t in extract_tables(doc) if t.lower() not in RESERVED)

    lines = [HEADER.format(version=version)]
    lines += [f'    {t}: LazyFrame = table("{t}")\n' for t in tables]
    OUT.write_text("".join(lines))
    print(f"wrote {len(tables)} tables to {OUT}")


if __name__ == "__main__":
    main()
