# run with `uv run python -m dev.gen_tables`
"""Regenerate ``fairfetched/get/_table_autocomplete.py``.

One ``<Source>Tables`` mix-in per dataset, one ``table(name)`` descriptor per
table in that source's latest release, so a language server and ``dir()`` expose
the full table set on ``<Source>.tables``. A table absent from an older release
raises ``AttributeError`` only on access. ChEMBL names come from the latest
published ``schema_documentation.txt``; the other sources' from their
``source_urls(latest())`` (flat files) or are fixed by their parser (DrugBank).
"""

from pathlib import Path

from dev.check_missing_tables import extract_tables, fetch_schema_doc
from fairfetched.get import (
    adrecs,
    adrecs_target,
    chembl,
    papyrus,
    sider,
    toxcast,
)

OUT = Path(__file__).parents[1] / "fairfetched" / "get" / "_table_autocomplete.py"

# names owned by _Base / _SourceTables; a table of the same name stays at lfs["<name>"].
RESERVED = {
    "version",
    "raw_paths",
    "parquet_paths",
    "dir",
    "module",
    "name",
    "sources",
    "lfs",
    "view",
    "raw_sql_db_path",
}

# DrugBank is licensed (no source_urls); drugbank.ensure_parquet_tables writes these four.
DRUGBANK_TABLES = ["drug", "biomolecule", "pathway", "drug_drug"]

HEADER = '''\
# generated by `uv run python -m dev.gen_tables`; do not edit by hand.
"""Raw source tables as attributes on ``<Dataset>.tables`` (:mod:`fairfetched.get.dataset`)."""

from polars import LazyFrame


def table(name: str) -> property:
    """Descriptor exposing ``self.lfs[name]`` as an attribute."""

    def _get(self) -> LazyFrame:
        try:
            return self.lfs[name]
        except KeyError:
            raise AttributeError(
                f"{name!r} is not a table in {self}; present: {sorted(self.lfs)}"
            ) from None

    return property(_get)

'''


def chembl_tables() -> list[str]:
    version = chembl.latest()
    doc = fetch_schema_doc(version)
    if not doc:
        raise SystemExit(f"could not fetch schema documentation for chembl {version}")
    return [t.lower() for t in extract_tables(doc)]


def flat_file_tables(
    module, drop: tuple[str, ...] = (), rename: dict | None = None
) -> list[str]:
    """Names in the latest ``source_urls``, minus non-table files (``drop``), after
    ``rename`` (source key -> table name, as passed to ``ensure_parquet_tables``)."""
    rename = rename or {}
    return [
        rename.get(k, k) for k in module.source_urls(module.latest()) if k not in drop
    ]


def tables_by_source() -> dict[str, list[str]]:
    """``<Source>Tables`` class name -> table names."""
    return {
        "ChemblTables": chembl_tables(),
        "PapyrusTables": flat_file_tables(papyrus, drop=("readme",)),
        "AdrecsTables": flat_file_tables(adrecs),
        "AdrecsTargetTables": flat_file_tables(adrecs_target),
        "SiderTables": flat_file_tables(sider, drop=("readme",)),
        "ToxcastTables": flat_file_tables(toxcast, rename=toxcast._TABLE_NAME),
        "DrugbankTables": DRUGBANK_TABLES,
    }


def render(by_source: dict[str, list[str]]) -> str:
    out = [HEADER]
    for cls, names in by_source.items():
        out.append(f"\nclass {cls}:\n")
        out += [
            f'    {t}: LazyFrame = table("{t}")\n'
            for t in sorted(set(names) - RESERVED)
        ]
    return "".join(out)


def main() -> None:
    by_source = tables_by_source()
    OUT.write_text(render(by_source))
    print(f"wrote {sum(map(len, by_source.values()))} tables to {OUT}")


if __name__ == "__main__":
    main()
