"""Chemistry correctness tests for `fairfetched.standardize`.

`test_standardize.py` covers plumbing: does an expression build, is the dtype
right, is the column non-null. Those tests all pass if `standardize()` quietly
becomes a no-op, so this file covers the other half -- whether the numbers
coming out are the right numbers, and whether the ways this module can fail are
visible to whoever is running it.

Expected values are taken from `tests/reference/standardize_reference.csv`, generated by
`tests/reference/generate.py`: So these tests compare fairfetched
against the underlying libraries (+ a published PubChem InChIKey where one exists).

Note: regenerate the file after upgrading RDKit or structure_pipelines

Dev note: current known 'bugs'/unimplementations are marked `xfail(strict=True)`.
Once fixed, these will 'fail' as unexpected passes: at that point, remove marker
"""

import logging
import warnings
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any

import polars as pl
import pytest
from rdkit import RDLogger
from rdkit.Chem import AddHs, Mol, MolFromSmiles, MolToSmiles

from fairfetched.standardize import mol_expr as me
from fairfetched.standardize.mol_expr import MolExpr
from fairfetched.standardize.mol_functions import (
    MolFn,
    _binary_to_inchikey,
    chembl_standardize,
    no_mixtures,
    only_organic,
    papyrus_standardize,
    remove_stereo,
    safe_step,
    valid_inchi,
    via_inchi,
)
from fairfetched.standardize.pipeline import STEPS_PAPYRUS, STEPS_PAPYRUS_NOSTEREO

RDLogger.DisableLog("rdApp.*")

pytest.importorskip("chembl_structure_pipeline")
pytest.importorskip("papyrus_structure_pipeline")


# builds the expression a sink test measures; kwargs are the dedup/parallel
# switches, which differ per sink
Sink = Callable[..., pl.Expr]

# one row of the reference table; the columns are the file's header, described
# in tests/reference/generate.py
MoleculeRow = dict[str, Any]

CASES_DF: pl.DataFrame = pl.read_csv(
    Path(__file__).parent / "reference" / "standardize_reference.csv",
    comment_prefix="#",
)
CASES: list[MoleculeRow] = CASES_DF.to_dicts()
MOLECULES: dict[str, MoleculeRow] = {row["name"]: row for row in CASES}
IDS: list[str] = list(MOLECULES)

# molecules whose structure ChEMBL standardization visibly changes
CHANGED: list[MoleculeRow] = [
    row for row in CASES if row["rdkit_smiles"] != row["chembl_smiles"]
]
CHANGED_IDS: list[str] = [row["name"] for row in CHANGED]

PUBLISHED: list[MoleculeRow] = [row for row in CASES if row["published_inchikey"]]
PUBLISHED_IDS: list[str] = [row["name"] for row in PUBLISHED]

# a repeating mix of duplicates, stereocentres and aromatics, for the tests that
# check a performance switch has not changed the answer
MIXED: list[str] = [
    MOLECULES["aspirin_aromatic"]["input_smiles"],
    "CCO",
    MOLECULES["caffeine"]["input_smiles"],
    "CCO",
    "c1ccccc1",
    MOLECULES["l_alanine"]["input_smiles"],
] * 4


def smi(name: str) -> str:
    return MOLECULES[name]["input_smiles"]


def keys(smiles: Iterable[str | None], *steps: MolFn) -> list[str | None]:
    """InChIKeys for `smiles` after running it through `steps`."""
    expr = MolExpr.from_smiles("smiles")
    if steps:
        expr = expr.standardize(*steps)
    df = pl.DataFrame({"smiles": list(smiles)})
    return df.with_columns(expr.to_inchikey().alias("k"))["k"].to_list()


def smis(smiles: Iterable[str | None], *steps: MolFn) -> list[str | None]:
    """Canonical SMILES for `smiles` after running it through `steps`."""
    expr = MolExpr.from_smiles("smiles")
    if steps:
        expr = expr.standardize(*steps)
    df = pl.DataFrame({"smiles": list(smiles)})
    return df.with_columns(expr.to_smiles().alias("s"))["s"].to_list()


def batch(sink: Sink, *steps: MolFn) -> dict[str, Any]:
    """Run `sink` once over the whole reference table -- a single query
    against real batch semantics, not 26 one-row queries -- and index the
    result by molecule name so parametrized tests can look up their row.
    """
    expr = MolExpr.from_smiles("input_smiles")
    if steps:
        expr = expr.standardize(*steps)
    out = CASES_DF.with_columns(computed=sink(expr))
    return dict(zip(out["name"], out["computed"], strict=True))


# each evaluated once at collection time; per-row tests below just look these up.
# Python equality on the scalar result (not a polars column `!=`) means a
# null-vs-non-null mismatch fails loudly instead of vanishing under Kleene logic.
RDKIT_SMILES = batch(lambda e: e.to_smiles())
CHEMBL_SMILES = batch(lambda e: e.to_smiles(), *me.STEPS_CHEMBL)
CHEMBL_INCHIKEY = batch(lambda e: e.to_inchikey(), *me.STEPS_CHEMBL)
CHEMBL_TWICE_INCHIKEY = batch(
    lambda e: e.to_inchikey(), *(me.STEPS_CHEMBL + me.STEPS_CHEMBL)
)
PAPYRUS_INCHIKEY = batch(lambda e: e.to_inchikey(), *STEPS_PAPYRUS)


def mol(smiles: str) -> Mol:
    """Parse a test input, failing loudly on a typo rather than passing None
    into a filter step that would quietly return None for it."""
    parsed = MolFromSmiles(smiles)
    assert parsed is not None, f"test input is not valid SMILES: {smiles!r}"
    return parsed


class TestStandardizationRuns:
    """A standardization step that silently stops running produces plausible
    output rather than an error, so these are the tests most worth having.
    """

    @pytest.mark.parametrize("row", CHANGED, ids=CHANGED_IDS)
    def test_chembl_changes_the_structure(self, row: MoleculeRow) -> None:
        """For these inputs the standardized output differs from what RDKit's
        SMILES parser produces on its own. Asserting both sides is the point: if
        the step stops running we get `rdkit_smiles` back and the test says so.
        """
        assert RDKIT_SMILES[row["name"]] == row["rdkit_smiles"]
        assert CHEMBL_SMILES[row["name"]] == row["chembl_smiles"]

    @pytest.mark.parametrize("row", CASES, ids=IDS)
    def test_unstandardized_output_is_plain_rdkit(self, row: MoleculeRow) -> None:
        """`from_smiles().to_smiles()` should be a parse and a canonicalisation
        and nothing more. If this drifts, the baseline the test above compares
        against stops being a baseline.
        """
        assert RDKIT_SMILES[row["name"]] == row["rdkit_smiles"]


class TestReferenceValues:
    """Catches a change in behaviour from upgrading RDKit or either structure
    pipeline. Most rows survive a no-op `standardize()` because InChI already
    normalises aromaticity and tautomers -- detecting a no-op is
    `TestStandardizationRuns`' job.
    """

    @pytest.mark.parametrize("row", CASES, ids=IDS)
    def test_chembl_inchikey(self, row: MoleculeRow) -> None:
        assert CHEMBL_INCHIKEY[row["name"]] == row["chembl_inchikey"]

    @pytest.mark.parametrize("row", CASES, ids=IDS)
    def test_papyrus_inchikey(self, row: MoleculeRow) -> None:
        """A null here is usually Papyrus rejecting the molecule rather than
        anything going wrong -- by default it drops everything outside
        200-800 Da. Pinning the nulls per molecule is what separates "filtered
        as designed" from "the whole column came back empty".
        """
        assert PAPYRUS_INCHIKEY[row["name"]] == row["papyrus_inchikey"]

    @pytest.mark.parametrize("row", PUBLISHED, ids=PUBLISHED_IDS)
    def test_shipped_reference_file_is_self_consistent(self, row: MoleculeRow) -> None:
        """This one asserts nothing about fairfetched. The CSV is generated but
        committed, so it can be hand-edited; this compares the two fields
        `generate.py` cross-checked at generation time and fails if someone has
        since changed one without the other. Fetching PubChem and aborting on a
        mismatch happens in `generate.py` -- nothing is fetched at test time.
        The key came from pubchem.ncbi.nlm.nih.gov/compound/<published_cid>.
        """
        assert row["chembl_inchikey"] == row["published_inchikey"]


class TestInvariants:
    """Properties that hold regardless of which molecule goes in, and that break
    loudly when a pipeline is subtly wrong.
    """

    @pytest.mark.parametrize("row", CASES, ids=IDS)
    def test_chembl_is_idempotent(self, row: MoleculeRow) -> None:
        """Running the pipeline twice should equal running it once. A step that
        keeps transforming its own output would show up as data that depends on
        how many times it happened to be standardized.
        """
        assert CHEMBL_TWICE_INCHIKEY[row["name"]] == row["chembl_inchikey"]

    @pytest.mark.parametrize(
        "group",
        [
            ["aspirin_kekule", "aspirin_aromatic", "aspirin_anion"],
            ["nitrobenzene_pentavalent", "nitrobenzene_reordered"],
        ],
        ids=["aspirin", "nitrobenzene"],
    )
    def test_equivalent_drawings_converge(self, group: list[str]) -> None:
        """One compound drawn several ways has to end up as one InChIKey,
        otherwise deduplicating a merged dataset by key silently keeps
        duplicates.
        """
        assert len(set(keys([smi(n) for n in group], *me.STEPS_CHEMBL))) == 1

    def test_salts_are_left_intact(self) -> None:
        """`STEPS_CHEMBL` is `standardize_mol` alone. Salt and solvent stripping
        lives in `get_parent_mol`, which `_optional.py` imports and then never
        exposes, so sodium acetate comes through as the salt.

        TODO: decide whether STEPS_CHEMBL should include get_parent_mol, or add
        a STEPS_CHEMBL_PARENT alongside it. "ChEMBL standardization" reads like
        the full pipeline and this is half of it.
        """
        row = MOLECULES["sodium_acetate_ionic"]
        assert keys([row["input_smiles"]], *me.STEPS_CHEMBL) == [row["chembl_inchikey"]]

    def test_only_alkali_metals_are_disconnected(self) -> None:
        """ChEMBL splits a covalent Na-O bond into ions but leaves Fe-O alone.
        That is upstream's rule, not a fairfetched decision -- `standardizer.py`
        matches `[Li,Na,K;+0:1]-[O+0:2]` and nothing else. Worth a test because
        "metal disconnection" sounds general and is not: an iron carboxylate and
        a sodium carboxylate leave the same pipeline in different forms.
        """
        for name in ("sodium_acetate_covalent", "iron_diacetate"):
            assert smis([smi(name)], *me.STEPS_CHEMBL) == [
                MOLECULES[name]["chembl_smiles"]
            ]


class TestStereochemistry:
    """Enantiomers and cis/trans pairs are different compounds, often with
    different activity. The existing suite checks stereo removal by looking for
    "@" in a SMILES string, which misses double-bond geometry entirely.
    """

    @pytest.mark.parametrize(
        "pair",
        [
            ("l_alanine", "d_alanine"),
            ("maleic_acid", "fumaric_acid"),
            ("naproxen_s", "naproxen_r"),
        ],
        ids=["tetrahedral", "double_bond", "naproxen"],
    )
    def test_stereoisomers_stay_distinct(self, pair: tuple[str, str]) -> None:
        assert len(set(keys([smi(n) for n in pair], *me.STEPS_CHEMBL))) == 2

    @pytest.mark.parametrize(
        "pair",
        [("l_alanine", "d_alanine"), ("maleic_acid", "fumaric_acid")],
        ids=["tetrahedral", "double_bond"],
    )
    def test_remove_stereo_collapses_both_kinds(self, pair: tuple[str, str]) -> None:
        """`remove_stereo` has to handle double-bond geometry as well as
        tetrahedral centres, so maleic and fumaric acid must come out identical.
        """
        collapsed = keys([smi(n) for n in pair], remove_stereo, *me.STEPS_CHEMBL)
        assert len(set(collapsed)) == 1
        assert collapsed[0] == MOLECULES[pair[0]]["chembl_nostereo_inchikey"]

    def test_papyrus_discards_stereochemistry_without_saying_so(self) -> None:
        """Papyrus defaults to `tautomer_allow_stereo_removal=True`, so plain
        `STEPS_PAPYRUS` destroys stereocentres on its own: (S)-naproxen comes
        back with a flat InChIKey while ChEMBL keeps the centre. Nothing in the
        return value distinguishes this from a molecule that never had
        stereochemistry.

        TODO: surface this. Either pass `tautomer_allow_stereo_removal=False` in
        STEPS_PAPYRUS, or have the papyrus steps warn once when a stereocentre
        is dropped. Right now a caller standardizing an enantiopure dataset with
        STEPS_PAPYRUS loses the stereochemistry with no indication it happened.
        """
        row = MOLECULES["naproxen_s"]
        chembl_key = keys([row["input_smiles"]], *me.STEPS_CHEMBL)[0]
        papyrus_key = keys([row["input_smiles"]], *STEPS_PAPYRUS)[0]

        assert chembl_key == row["chembl_inchikey"]
        assert papyrus_key == row["papyrus_inchikey"]
        assert chembl_key.split("-")[1] != "UHFFFAOYSA"  # ChEMBL kept the centre
        assert papyrus_key.split("-")[1] == "UHFFFAOYSA"  # Papyrus flattened it

        warnings.warn(
            "STEPS_PAPYRUS discarded the (S) stereocentre of naproxen "
            f"({chembl_key} -> {papyrus_key}) and the API gives the caller no "
            "way to detect it. See the TODO in this test.",
            UserWarning,
            stacklevel=2,
        )

    def test_papyrus_nostereo_differs_from_papyrus(self) -> None:
        """Because Papyrus often removes stereochemistry by itself, the two step
        lists give the same answer for most inputs and `STEPS_PAPYRUS_NOSTEREO`
        looks redundant. Cholesterol is a case where stereochemistry does
        survive Papyrus, so prepending `remove_stereo` has a visible effect and
        the two lists can be told apart.
        """
        row = MOLECULES["cholesterol"]
        assert keys([row["input_smiles"]], *STEPS_PAPYRUS) == [row["papyrus_inchikey"]]
        assert keys([row["input_smiles"]], *STEPS_PAPYRUS_NOSTEREO) == [
            row["papyrus_nostereo_inchikey"]
        ]
        assert row["papyrus_inchikey"] != row["papyrus_nostereo_inchikey"]

    @pytest.mark.parametrize("name", ["dexamethasone", "testosterone"])
    def test_papyrus_can_return_a_different_skeleton_than_chembl(
        self, name: str
    ) -> None:
        """For these two the pipelines disagree on the first block of the
        InChIKey, which means the connectivity itself differs -- Papyrus'
        tautomer canonicalisation moved a proton. Choosing a pipeline is a
        chemistry decision, not a formatting one: keys from the two cannot be
        used to join datasets together.

        TODO: document this in the README next to STEPS_CHEMBL / STEPS_PAPYRUS.
        """
        row = MOLECULES[name]
        chembl_key = keys([row["input_smiles"]], *me.STEPS_CHEMBL)[0]
        papyrus_key = keys([row["input_smiles"]], *STEPS_PAPYRUS)[0]
        assert chembl_key == row["chembl_inchikey"]
        assert papyrus_key == row["papyrus_inchikey"]
        assert chembl_key.split("-")[0] != papyrus_key.split("-")[0]


class TestFailureModes:
    """`safe_step` turns every exception into None, so "this molecule was
    rejected by a chemistry rule", "RDKit threw", and "the optional dependency
    is missing" all look identical in the output column.
    """

    def test_unparseable_smiles_null_only_their_own_rows(self) -> None:
        smiles = ["CCO", "not_a_smiles", "c1ccccc", "CCC", "CC(C"]
        assert [k is None for k in keys(smiles)] == [False, True, True, False, True]

    def test_null_input_stays_null(self) -> None:
        df = pl.DataFrame({"smiles": ["CCO", None, "CCC"]})
        out = df.with_columns(
            MolExpr.from_smiles("smiles")
            .standardize(*me.STEPS_CHEMBL)
            .to_smiles()
            .alias("s")
        )
        assert out["s"].to_list() == ["CCO", None, "CCC"]

    def test_step_with_a_wrong_return_type_raises(self) -> None:
        """`MolPipeline.__call__` is not itself wrapped in `safe_step`, so a step
        returning something that is not a Mol surfaces as an error instead of a
        column of nulls. Worth keeping that way.
        """
        df = pl.DataFrame({"smiles": ["CCO"]})
        with pytest.raises(AttributeError):
            df.with_columns(
                MolExpr.from_smiles("smiles")
                .standardize(lambda m: "not a mol")
                .alias("m")
            )

    def test_wrapped_and_unwrapped_steps_fail_differently(self) -> None:
        """`STEPS_CHEMBL` holds the `safe_step`-wrapped `chembl_standardize`,
        while `STEPS_PAPYRUS` holds the raw `_papyrus_standardize` straight from
        `_optional.py`. So the same kind of failure nulls the column in one
        pipeline and kills the query in the other.
        `mol_functions.papyrus_standardize` is the wrapped version and nothing
        imports it.

        TODO: pick one. Either wrap both (consistent, silent) or neither
        (consistent, loud); the current split means error handling depends on
        which pipeline you picked.
        """
        assert me.STEPS_CHEMBL[0] is chembl_standardize
        assert STEPS_PAPYRUS[-1] is not papyrus_standardize

        def boom(mol):
            raise RuntimeError("standardization failed")

        df = pl.DataFrame({"smiles": ["CCO"]})
        with pytest.raises(RuntimeError):
            df.with_columns(MolExpr.from_smiles("smiles").standardize(boom).alias("m"))

        logging.disable(logging.CRITICAL)
        try:
            out = df.with_columns(
                MolExpr.from_smiles("smiles")
                .standardize(safe_step(boom))
                .to_smiles()
                .alias("s")
            )
        finally:
            logging.disable(logging.NOTSET)
        assert out["s"].to_list() == [None]

    @pytest.mark.xfail(
        strict=True,
        reason="safe_step swallows the ImportError raised by the _optional.py "
        "placeholder, so a missing chembl_structure_pipeline gives a column of "
        "nulls instead of an error",
    )
    def test_missing_optional_dependency_raises(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """When `chembl_structure_pipeline` is not installed, `_optional.py`
        substitutes a placeholder that raises ImportError when called.
        `safe_step` catches it, so every row comes back null and the run looks
        like it worked on a difficult dataset.

        TODO: let ImportError through in `safe_step`, or check for the
        placeholder when a pipeline is built rather than per molecule.
        """
        import fairfetched.standardize.mol_functions as mf

        def missing_dependency(mol, *args, **kwargs):
            raise ImportError("chembl_structure_pipeline not installed")

        monkeypatch.setattr(mf, "_chembl_standardize", missing_dependency)
        logging.disable(logging.CRITICAL)
        try:
            df = pl.DataFrame({"smiles": ["CCO"] * 3})
            with pytest.raises(Exception):
                df.with_columns(
                    MolExpr.from_smiles("smiles")
                    .standardize(mf.chembl_standardize)
                    .to_smiles()
                    .alias("s")
                )
        finally:
            logging.disable(logging.NOTSET)


class TestColumnContracts:
    """What the expressions promise about the frame they hand back: which
    columns they create, which they must not touch, and the dtypes they declare.
    """

    @pytest.mark.xfail(
        strict=True,
        reason="to_descriptors() unnests a struct field called 'smiles', which "
        "overwrites the caller's input column with kekulized, non-isomeric SMILES",
    )
    def test_to_descriptors_leaves_the_input_column_alone(self) -> None:
        """`Descriptors` has a field named `smiles`, so `struct.unnest()` writes
        over an input column of the same name -- and the replacement is
        non-isomeric, so stereochemistry disappears from the caller's source
        data.

        TODO: rename the field to `kekulized_smiles`, or prefix the unnested
        columns, or raise on collision. Silently rewriting an input column is
        the worst of the three options.
        """
        df = pl.DataFrame({"id": [1, 2], "smiles": [smi("l_alanine"), "CCO"]})
        out = df.with_columns(MolExpr.from_smiles("smiles").to_descriptors())
        assert out["smiles"].to_list() == df["smiles"].to_list()

    def test_descriptor_fields_agree_with_the_single_value_sinks(self) -> None:
        """`to_descriptors()` computes several values in one pass. Those have to
        match what the individual sinks return, or which method you call changes
        the answer.
        """
        df = pl.DataFrame({"input": [smi("aspirin_aromatic"), "CCO"]})
        out = df.with_columns(
            MolExpr.from_smiles("input").to_descriptors(),
            MolExpr.from_smiles("input").to_inchikey().alias("separate_key"),
            MolExpr.from_smiles("input").to_inchi().alias("separate_inchi"),
        )
        assert out["inchikey"].to_list() == out["separate_key"].to_list()
        assert out["inchi"].to_list() == out["separate_inchi"].to_list()

    @pytest.mark.parametrize("empty", [True, False], ids=["empty", "all_null"])
    @pytest.mark.xfail(
        strict=True,
        reason="from_col_infer returns the input String series untouched when "
        "it finds no non-null value, violating its declared pl.Binary return type",
    )
    def test_from_col_infer_handles_nothing_to_infer_from(self, empty: bool) -> None:
        """`_infer` looks for the first non-null value to decide between SMILES
        and InChI. With nothing to look at it returns the String series
        unchanged, and polars rejects it against the declared Binary dtype -- so
        an empty partition crashes a query that works fine on a full one.

        TODO: return a null Binary series of the right length instead.
        """
        data = [] if empty else [None, None]
        df = pl.DataFrame({"s": data}, schema={"s": pl.String})
        out = df.with_columns(MolExpr.from_col_infer("s").to_smiles().alias("out"))
        assert out["out"].to_list() == data

    def test_from_col_infer_picks_the_right_parser(self) -> None:
        """The same compound as SMILES and as InChI has to land on one key."""
        inchi = "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3"
        expected = MOLECULES["ethanol"]["rdkit_inchikey"]
        for value in ("CCO", inchi):
            df = pl.DataFrame({"s": [value]})
            out = df.with_columns(MolExpr.from_col_infer("s").to_inchikey().alias("k"))
            assert out["k"].to_list() == [expected]

    def test_from_inchi_round_trips(self) -> None:
        df = pl.DataFrame({"inchi": ["InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3"]})
        out = df.with_columns(MolExpr.from_inchi("inchi").to_inchi().alias("back"))
        assert out["back"].to_list() == df["inchi"].to_list()


class TestExecutionModes:
    """`parallel` and `dedup` are performance switches. Neither is allowed to
    change the answer, and nothing in the type system stops them.
    """

    def test_parallel_matches_serial(self) -> None:
        df = pl.DataFrame({"smiles": MIXED})
        serial = df.with_columns(
            MolExpr.from_smiles("smiles")
            .standardize(*me.STEPS_CHEMBL)
            .to_inchikey()
            .alias("k")
        )
        parallel = df.with_columns(
            MolExpr.from_smiles("smiles", parallel=True)
            .standardize(*me.STEPS_CHEMBL, parallel=True)
            .to_inchikey(parallel=True)
            .alias("k")
        )
        assert serial["k"].to_list() == parallel["k"].to_list()

    def test_parallel_fallback_is_at_least_logged(
        self, caplog: pytest.LogCaptureFixture
    ) -> None:
        """An unpicklable step makes the process pool fail. `_map_nodedup`
        catches everything and reruns serially, so the answer is still right but
        a broken parallel path is indistinguishable from a slow one. The log
        entry is the only signal, so keep it.
        """
        df = pl.DataFrame({"smiles": ["CCO"] * 4})
        with caplog.at_level(logging.ERROR):
            out = df.with_columns(
                MolExpr.from_smiles("smiles")
                .standardize(lambda m: m, parallel=True)
                .to_smiles()
                .alias("s")
            )
        assert out["s"].to_list() == ["CCO"] * 4
        assert "resorting to native polars" in caplog.text

    @pytest.mark.parametrize(
        "sink",
        [
            # to_smiles/to_inchi/to_inchikey take no dedup argument, unlike
            # to_descriptors/to_morgan_fp/num_atoms; to_custom is the only
            # String-returning sink that does
            lambda expr, **kw: expr.to_custom(
                _binary_to_inchikey, pl.String, **kw
            ).alias("v"),
            lambda expr, **kw: expr.to_morgan_fp(fp_size=256, **kw).alias("v"),
            lambda expr, **kw: expr.num_heavy_atoms(**kw).alias("v"),
        ],
        ids=["string", "array", "int"],
    )
    def test_dedup_matches_nodedup(self, sink: Sink) -> None:
        """`_map` computes on unique values and re-expands with a left join.
        Polars makes no row-order promise for a join unless you pass
        `maintain_order`, and the mapping is declared elementwise, so this checks
        the rows still line up. Run across return types because a Struct or
        Array column goes through the join differently than a String one.

        TODO: dedup is missing from to_smiles/to_inchi/to_inchikey/
        to_kekulized_smiles for no obvious reason -- add it there, or drop it
        from the others.
        """
        df = pl.DataFrame({"smiles": MIXED})
        plain = df.with_columns(sink(MolExpr.from_smiles("smiles")))
        deduped = df.with_columns(
            sink(MolExpr.from_smiles("smiles", dedup=True), dedup=True)
        )
        assert plain["v"].to_list() == deduped["v"].to_list()
        assert plain["v"].dtype == deduped["v"].dtype

    def test_dedup_matches_nodedup_for_struct_output(self) -> None:
        df = pl.DataFrame({"input": MIXED})
        plain = df.with_columns(MolExpr.from_smiles("input").to_descriptors())
        deduped = df.with_columns(
            MolExpr.from_smiles("input").to_descriptors(dedup=True)
        )
        assert plain.equals(deduped)

    def test_dedup_keeps_nulls_in_place(self) -> None:
        """Nulls are join keys too, and polars does not match null to null by
        default. Rows must not shift.
        """
        df = pl.DataFrame({"smiles": ["CCO", None, "CCC", None, "CCO"]})
        out = df.with_columns(
            MolExpr.from_smiles("smiles", dedup=True).to_smiles().alias("s")
        )
        assert out["s"].to_list() == ["CCO", None, "CCC", None, "CCO"]


class TestFilterSteps:
    """These decide which molecules leave the dataset. Both `no_mixtures` and
    `only_organic` log that they are untested naive implementations; this is
    that test.
    """

    @pytest.mark.parametrize(
        "smiles,kept",
        [("CCO", True), ("CC(=O)Oc1ccccc1C(=O)O", True), ("[Na+].CC(=O)[O-]", False)],
        ids=["ethanol", "aspirin", "sodium_acetate"],
    )
    def test_no_mixtures(self, smiles: str, kept: bool) -> None:
        """Implemented as a "." check on the SMILES, which is why a salt counts
        as a mixture. That is the intended reading for most datasets, but it
        also drops anything else written as disconnected components.
        """
        assert (no_mixtures(mol(smiles)) is not None) == kept

    @pytest.mark.parametrize(
        "smiles,kept",
        [
            ("CCO", True),
            ("ClCCBr", True),
            ("[Fe]", False),
            ("OB(O)c1ccccc1", False),
            ("C[Si](C)C", False),
        ],
        ids=["ethanol", "halogenated", "iron", "boronic_acid", "silane"],
    )
    def test_only_organic(self, smiles: str, kept: bool) -> None:
        """The element set is {C,N,O,F,P,S,Cl,Br,I}, so boron and silicon are
        out. That rules out boronic acids and organosilicons, which a medicinal
        chemist would call organic.

        TODO: decide whether B, Si and Se belong in the set. Also fix the
        docstring on only_organic -- it says "returns none if mol is organic",
        which is the opposite of what the code does.
        """
        assert (only_organic(mol(smiles)) is not None) == kept

    @pytest.mark.xfail(
        strict=True,
        reason="only_organic's element set omits atomic number 1, so any "
        "molecule carrying explicit hydrogens is rejected",
    )
    def test_only_organic_accepts_explicit_hydrogens(self) -> None:
        """Explicit hydrogens are normal after `Chem.AddHs`, which anything
        doing 3D work will have called. Every such molecule is currently
        dropped.

        TODO: add 1 to the organic element set.
        """
        assert only_organic(AddHs(mol("CCO"))) is not None

    def test_valid_inchi_keeps_representable_molecules(self) -> None:
        assert valid_inchi(mol(smi("aspirin_aromatic"))) is not None

    def test_via_inchi_preserves_the_molecule(self) -> None:
        """A round trip through InChI has to give the compound back. Anything
        InChI cannot represent comes back as None instead, which is the
        silent-drop path worth knowing about when this step is in a pipeline.
        """
        result = via_inchi(mol(smi("aspirin_aromatic")))
        assert result is not None
        assert MolToSmiles(result) == MOLECULES["aspirin_aromatic"]["rdkit_smiles"]
