"""Tiny offline sample datasets for docstrings and tests.

``Chembl.demo()`` / ``Papyrus.demo()`` / ``Toxcast.demo()`` load the parquet
tables under ``_demo/<dataset>/``: row slices of the real releases (ChEMBL 37,
Papyrus 05.7, ToxCast 4.3), regenerated by ``uv run python -m dev.gen_demos``.
"""

from pathlib import Path

DEMO_DIR = Path(__file__).parent / "_demo"


def parquets(dataset: str) -> dict[str, Path]:
    return {p.stem: p for p in sorted((DEMO_DIR / dataset).glob("*.parquet"))}
