"""Attribute access to raw source tables on the dataset wrappers.

The ``*Tables`` mix-ins (``_chembl_tables.py`` is generated by
``dev/gen_tables.py``; ``_papyrus_tables.py`` is hand-kept) list one
``table(name)`` descriptor per table in the latest published schema, so a
language server and ``dir()`` show the full set. A table absent from the loaded
version raises ``AttributeError`` only when accessed.
"""

from polars import LazyFrame


def table(name: str) -> property:
    """Descriptor exposing ``self.lfs[name]`` as an attribute."""

    def _get(self) -> LazyFrame:
        try:
            return self.lfs[name]
        except KeyError:
            raise AttributeError(
                f"{name!r} is not a table in {self}; present: {sorted(self.lfs)}"
            ) from None

    return property(_get)
