# mol_expr.pyi
import polars as pl

from .mol_expr import MolExprs, MolFn

# class MolExpr:
#     def __init__(self, expr: pl.Expr) -> None: ...
#     def from_smiles(self) -> pl.Expr: ...
#     def from_inchi(self) -> pl.Expr: ...
#     def to_smiles(self) -> pl.Expr: ...
#     def to_inchi(self) -> pl.Expr: ...
#     def to_inchikey(self) -> pl.Expr: ...
#     def to_kekulised_smiles(self) -> pl.Expr: ...
#     def num_atoms(self) -> pl.Expr: ...
#     def num_heavy_atoms(self) -> pl.Expr: ...
#     def standardise(self, *steps: MolFn) -> pl.Expr: ...

# teach ty that pl.Expr has a .mol accessor
class _ExprMolAccessor:
    mol: MolExprs

# ty picks this up via the __getattr__ extension pattern
def __getattr__(name: str) -> MolExprs: ...
